### ISSUE TITLE
BUG: sqlite database disk image is malformed with threading (PROJ 8.1+)

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#2843] opened 2021-09-06 17:43 UTC
From: https://github.com/pyproj4/pyproj/issues/933
Related to: https://github.com/OSGeo/PROJ/pull/2738

#### Example of problem
Not sure the best way to re-produce this issue in `c` code. But, it is essentially the `proj_create` call in parallel.

Error message:
```
terminate called after throwing an instance of 'terminate called after throwing an instance of 'osgeo::proj::io::FactoryExceptionosgeo::proj::io::FactoryException'
'
  what():    what():  SQLite error on SELECT alt_name FROM alias_name WHERE table_name = ? AND auth_name = ? AND code = ?: database disk image is malformed
SQLite error on SELECT alt_name FROM alias_name WHERE table_name = ? AND auth_name = ? AND code = ?: database disk image is malformed
```
#### Problem description

Someone found a way to demonstrate that this isn't thread safe: https://github.com/OSGeo/PROJ/pull/2738

#### Environment Information

No issue with PROJ 8.0.1 with autoclose DB. There is an issue with PROJ 8.1.1

**Comment by snowman2** [comment] 2021-09-06 17:48
Here is the output from PROJ debugging:
```
DEBUG:PROJ_DEBUG: pj_open_lib(proj.ini): call fopen(/home/snowal/miniconda/envs/proj81/share/proj/proj.ini) - succeeded
DEBUG:PROJ_TRACE: pipeline: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
DEBUG:PROJ_TRACE: pipeline: pj_ellipsoid - final:    ellps=GRS80
DEBUG:PROJ_TRACE: pipeline: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
DEBUG:PROJ_TRACE: pipeline: pj_ellipsoid - final:    
DEBUG:PROJ_TRACE: pipeline: Pipeline: Building arg list for step no. 0
DEBUG:PROJ_TRACE: pipeline: Pipeline: init - proj=axisswap, 2
DEBUG:PROJ_TRACE: pipeline:     order=2,1
DEBUG:PROJ_TRACE: axisswap: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
DEBUG:PROJ_TRACE: axisswap: pj_ellipsoid - final:    ellps=GRS80
DEBUG:PROJ_TRACE: pipeline: Pipeline: Step 0 (proj=axisswap) at 0x55c59f8fcf50
DEBUG:PROJ_TRACE: pipeline: Pipeline at [0x55c59f8fb020]:    step at [0x55c59f8fcf50] (proj=axisswap) done
DEBUG:PROJ_TRACE: pipeline: Pipeline: Building arg list for step no. 1
DEBUG:PROJ_TRACE: pipeline: Pipeline: init - proj=unitconvert, 3
DEBUG:PROJ_TRACE: pipeline:     xy_in=deg
DEBUG:PROJ_TRACE: pipeline:     xy_out=rad
DEBUG:PROJ_TRACE: unitconvert: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
DEBUG:PROJ_TRACE: unitconvert: pj_ellipsoid - final:    ellps=GRS80
DEBUG:PROJ_TRACE: unitconvert: xy_in unit: Degree
DEBUG:PROJ_TRACE: unitconvert: xy_out unit: Radian
DEBUG:PROJ_TRACE: pipeline: Pipeline: Step 1 (proj=unitconvert) at 0x55c59f909cc0
DEBUG:PROJ_TRACE: pipeline: Pipeline at [0x55c59f8fb020]:    step at [0x55c59f909cc0] (proj=unitconvert) done
DEBUG:PROJ_TRACE: pipeline: Pipeline: Building arg list for step no. 2
DEBUG:PROJ_TRACE: pipeline: Pipeline: init - proj=utm, 3
DEBUG:PROJ_TRACE: pipeline:     zone=35
DEBUG:PROJ_TRACE: pipeline:     ellps=GRS80
DEBUG:PROJ_TRACE: utm: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
DEBUG:PROJ_TRACE: utm: pj_ellipsoid - final:    ellps=GRS80
DEBUG:PROJ_TRACE: pipeline: Pipeline: Step 2 (proj=utm) at 0x55c59f90a240
DEBUG:PROJ_TRACE: pipeline: Pipeline at [0x55c59f8fb020]:    step at [0x55c59f90a240] (proj=utm) done
DEBUG:PROJ_TRACE: pipeline: Pipeline: 3 steps built. Determining i/o characteristics
DEBUG:PROJ_DEBUG: pj_open_lib(proj.ini): call fopen(/home/snowal/miniconda/envs/proj81/share/proj/proj.ini) - succeeded
DEBUG:PROJ_TRACE: pipeline: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
DEBUG:PROJ_ERROR: proj_create: SQLite error on SELECT auth_name FROM authority_list: database disk image is malformed
DEBUG:PROJ_TRACE: pipeline: pj_ellipsoid - final:    ellps=GRS80
DEBUG:PROJ_TRACE: pipeline: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
DEBUG:PROJ_TRACE: pipeline: pj_ellipsoid - final:    
DEBUG:PROJ_TRACE: pipeline: Pipeline: Building arg list for step no. 0
DEBUG:PROJ_TRACE: pipeline: Pipeline: init - proj=axisswap, 2
DEBUG:PROJ_TRACE: pipeline:     order=2,1
DEBUG:PROJ_TRACE: axisswap: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
DEBUG:PROJ_TRACE: axisswap: pj_ellipsoid - final:    ellps=GRS80
DEBUG:PROJ_TRACE: pipeline: Pipeline: Step 0 (proj=axisswap) at 0x55c59f8b8bc0
DEBUG:PROJ_TRACE: pipeline: Pipeline at [0x55c59f640de0]:    step at [0x55c59f8b8bc0] (proj=axisswap) done
DEBUG:PROJ_TRACE: pipeline: Pipeline: Building arg list for step no. 1
DEBUG:PROJ_TRACE: pipeline: Pipeline: init - proj=unitconvert, 3
DEBUG:PROJ_TRACE: pipeline:     xy_in=deg
DEBUG:PROJ_TRACE: pipeline:     xy_out=rad
DEBUG:PROJ_TRACE: unitconvert: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
DEBUG:PROJ_TRACE: unitconvert: pj_ellipsoid - final:    ellps=GRS80
DEBUG:PROJ_TRACE: unitconvert: xy_in unit: Degree
DEBUG:PROJ_TRACE: unitconvert: xy_out unit: Radian
DEBUG:PROJ_TRACE: pipeline: Pipeline: Step 1 (proj=unitconvert) at 0x55c59f8a5540
DEBUG:PROJ_TRACE: pipeline: Pipeline at [0x55c59f640de0]:    step at [0x55c59f8a5540] (proj=unitconvert) done
DEBUG:PROJ_TRACE: pipeline: Pipeline: Building arg list for step no. 2
DEBUG:PROJ_TRACE: pipeline: Pipeline: init - proj=utm, 3
DEBUG:PROJ_TRACE: pipeline:     zone=35
DEBUG:PROJ_TRACE: pipeline:     ellps=GRS80
DEBUG:PROJ_TRACE: utm: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
DEBUG:PROJ_TRACE: utm: pj_ellipsoid - final:    ellps=GRS80
DEBUG:PROJ_TRACE: pipeline: Pipeline: Step 2 (proj=utm) at 0x55c59f8a5a80
DEBUG:PROJ_TRACE: pipeline: Pipeline at [0x55c59f640de0]:    step at [0x55c59f8a5a80] (proj=utm) done
DEBUG:PROJ_TRACE: pipeline: Pipeline: 3 steps built. Determining i/o characteristics
DEBUG:PROJ_ERROR: proj_create: SQLite error on SELECT auth_name FROM authority_list: database disk image is malformed
DEBUG:PROJ_ERROR: proj_create: SQLite error on SELECT auth_name FROM authority_list: database disk image is malformed
DEBUG:PROJ_DEBUG: pj_open_lib(proj.ini): call fopen(/home/snowal/miniconda/envs/proj81/share/proj/proj.ini) - succeeded
DEBUG:PROJ_TRACE: pipeline: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
DEBUG:PROJ_TRACE: pipeline: pj_ellipsoid - final:    ellps=GRS80
DEBUG:PROJ_TRACE: pipeline: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
DEBUG:PROJ_TRACE: pipeline: pj_ellipsoid - final:    
DEBUG:PROJ_TRACE: pipeline: Pipeline: Building arg list for step no. 0
DEBUG:PROJ_TRACE: pipeline: Pipeline: init - proj=axisswap, 2
DEBUG:PROJ_TRACE: pipeline:     order=2,1
DEBUG:PROJ_TRACE: axisswap: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
DEBUG:PROJ_TRACE: axisswap: pj_ellipsoid - final:    ellps=GRS80
DEBUG:PROJ_TRACE: pipeline: Pipeline: Step 0 (proj=axisswap) at 0x55c59f8fd690
DEBUG:PROJ_TRACE: pipeline: Pipeline at [0x55c59f8fb760]:    step at [0x55c59f8fd690] (proj=axisswap) done
DEBUG:PROJ_TRACE: pipeline: Pipeline: Building arg list for step no. 1
DEBUG:PROJ_TRACE: pipeline: Pipeline: init - proj=unitconvert, 3
DEBUG:PROJ_TRACE: pipeline:     xy_in=deg
DEBUG:PROJ_TRACE: pipeline:     xy_out=rad
DEBUG:PROJ_TRACE: unitconvert: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
DEBUG:PROJ_TRACE: unitconvert: pj_ellipsoid - final:    ellps=GRS80
DEBUG:PROJ_TRACE: unitconvert: xy_in unit: Degree
DEBUG:PROJ_TRACE: unitconvert: xy_out unit: Radian
DEBUG:PROJ_TRACE: pipeline: Pipeline: Step 1 (proj=unitconvert) at 0x55c59f90a400
DEBUG:PROJ_TRACE: pipeline: Pipeline at [0x55c59f8fb760]:    step at [0x55c59f90a400] (proj=unitconvert) done
DEBUG:PROJ_TRACE: pipeline: Pipeline: Building arg list for step no. 2
DEBUG:PROJ_TRACE: pipeline: Pipeline: init - proj=utm, 3
DEBUG:PROJ_TRACE: pipeline:     zone=35
DEBUG:PROJ_TRACE: pipeline:     ellps=GRS80
DEBUG:PROJ_TRACE: utm: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
DEBUG:PROJ_TRACE: utm: pj_ellipsoid - final:    ellps=GRS80
DEBUG:PROJ_TRACE: pipeline: Pipeline: Step 2 (proj=utm) at 0x55c59f90a980
DEBUG:PROJ_TRACE: pipeline: Pipeline at [0x55c59f8fb760]:    step at [0x55c59f90a980] (proj=utm) done
DEBUG:PROJ_TRACE: pipeline: Pipeline: 3 steps built. Determining i/o characteristics
DEBUG:PROJ_ERROR: proj_create: SQLite error on SELECT auth_name FROM authority_list: database disk image is malformed
DEBUG:PROJ_ERROR: proj_create: SQLite error on SELECT auth_name FROM authority_list: database disk image is malformed
DEBUG:PROJ_ERROR: proj_create: SQLite error on SELECT auth_name FROM authority_list: database disk image is malformed
DEBUG:PROJ_DEBUG: pj_open_lib(proj.ini): call fopen(/home/snowal/miniconda/envs/proj81/share/proj/proj.ini) - succeeded
DEBUG:PROJ_TRACE: pipeline: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
DEBUG:PROJ_TRACE: pipeline: pj_ellipsoid - final:    ellps=GRS80
DEBUG:PROJ_TRACE: pipeline: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
DEBUG:PROJ_TRACE: pipeline: pj_ellipsoid - final:    
DEBUG:PROJ_TRACE: pipeline: Pipeline: Building arg list for step no. 0
DEBUG:PROJ_TRACE: pipeline: Pipeline: init - proj=axisswap, 2
DEBUG:PROJ_TRACE: pipeline:     order=2,1
DEBUG:PROJ_TRACE: axisswap: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
DEBUG:PROJ_TRACE: axisswap: pj_ellipsoid - final:    ellps=GRS80
DEBUG:PROJ_TRACE: pipeline: Pipeline: Step 0 (proj=axisswap) at 0x55c59f64d1c0
DEBUG:PROJ_TRACE: pipeline: Pipeline at [0x55c59f8b0780]:    step at [0x55c59f64d1c0] (proj=axisswap) done
DEBUG:PROJ_TRACE: pipeline: Pipeline: Building arg list for step no. 1
DEBUG:PROJ_TRACE: pipeline: Pipeline: init - proj=unitconvert, 3
DEBUG:PROJ_TRACE: pipeline:     xy_in=deg
DEBUG:PROJ_TRACE: pipeline:     xy_out=rad
DEBUG:PROJ_TRACE: unitconvert: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
DEBUG:PROJ_TRACE: unitconvert: pj_ellipsoid - final:    ellps=GRS80
DEBUG:PROJ_TRACE: unitconvert: xy_in unit: Degree
DEBUG:PROJ_TRACE: unitconvert: xy_out unit: Radian
DEBUG:PROJ_TRACE: pipeline: Pipeline: Step 1 (proj=unitconvert) at 0x55c59f67b400
DEBUG:PROJ_TRACE: pipeline: Pipeline at [0x55c59f8b0780]:    step at [0x55c59f67b400] (proj=unitconvert) done
DEBUG:PROJ_TRACE: pipeline: Pipeline: Building arg list for step no. 2
DEBUG:PROJ_TRACE: pipeline: Pipeline: init - proj=utm, 3
DEBUG:PROJ_TRACE: pipeline:     zone=35
DEBUG:PROJ_TRACE: pipeline:     ellps=GRS80
DEBUG:PROJ_TRACE: utm: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
DEBUG:PROJ_TRACE: utm: pj_ellipsoid - final:    ellps=GRS80
DEBUG:PROJ_TRACE: pipeline: Pipeline: Step 2 (proj=utm) at 0x55c59f67b7c0
DEBUG:PROJ_TRACE: pipeline: Pipeline at [0x55c59f8b0780]:    step at [0x55c59f67b7c0] (proj=utm) done
DEBUG:PROJ_TRACE: pipeline: Pipeline: 3 steps built. Determining i/o characteristics
```

**Comment by rouault** [comment] 2021-09-06 17:58
is the use case using a fork() strategy (child processes) or a threading strategy ? I'd expect the fork() strategy not to work if an access to the database has been done before forking, because then the parent and child processes will use the same open file descriptor.
Releasing all PROJ contexts, and calling proj_cleanup() before fork() could be a workaround

**Comment by snowman2** [comment] 2021-09-06 18:08
https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor

Looks like the fork strategy based on what I can tell.

**Comment by snowman2** [comment] 2021-09-06 18:18
> because then the parent and child processes will use the same open file descriptor.

For some reason I thought that the change allowed different threads sharing the same file handle. If that is not the case, the the autoclose db logic will be needed again as you will run into the limit of the number of file handles you have open (#1565) with a lot of threads.

**Comment by snowman2** [comment] 2021-09-06 18:27
> Releasing all PROJ contexts, and calling proj_cleanup() before fork() could be a workaround

Each pyproj object has its own PROJ context, so all of them would need to be deleted before doing threading and re-created afterwards.

**Comment by rouault** [comment] 2021-09-06 18:28
hum so I have in GDAL this https://github.com/OSGeo/gdal/blob/master/autotest/cpp/proj_with_fork.cpp test program that tests such a situation. Before PROJ 8.1.1, there was a workaround in GDAL (GDAL uses a per-thread PROJ context), https://github.com/OSGeo/gdal/commit/095bc422fcccfd66ca3597c5c6faa1368235f6b5, to detect if the process id has changed, and if so it explicitly called proj_context_set_autoclose_database(..., false) to force the database closing and re-opened afterwards. Now with PROJ 8.1.1, this is essentially a no-op, but the test still works. Looking at strace output and sqlite3 source code, it uses the pread64() system call which enables to do a seek()+read() in the same system call (in particular to address issues with multi-threading), and thus share the same open file handle in several threads. Hum, so I'm really puzzled now why the above mentioned commit was necessary at all in the first place given my theory with pread64() (my theory is likely wrong, perhaps pread64() is not fork() safe), and why my proj_with_fork GDAL test still passes.

> For some reason I thought that the change allowed different threads sharing the same file handle. 

It does. But threads != processes. I'm realizing it is difficult to have both thread-safe and forked-process-safe code. I'm quite confident that the issue here is fork() specific.

**Comment by snowman2** [comment] 2021-09-06 18:30
> Releasing all PROJ contexts, and calling proj_cleanup() before fork() could be a workaround

Another question about this is the global context. Could that mess things up too?

**Comment by rouault** [comment] 2021-09-06 18:35
> Another question about this is the global context. Could that mess things up too?

using the global context in parent and child/children accros fork(), if they are single-threaded, should not be a problem (besides a potential issue with SQLite3 accesses)

Basically I would need a C level reproducer.

**Comment by rouault** [comment] 2021-09-06 20:04
strong suspicion this is due to the sqlite3 build bundled with pyproj binary wheels: https://github.com/pyproj4/pyproj/issues/933#issuecomment-913832744

**Closed as completed** 2021-09-08 11:17 UTC
Labels: bug
