### ISSUE TITLE
cct skips last line of input file

### ISSUE THREAD

**Issue by Andre-J** [OSGeo/PROJ#1166] opened 2018-10-28 17:45 UTC
Either using
<code>
cct -z 0 +proj=helmert +convention=coordinate_frame +x=239228.435 +y=6693404.951 +s=1.0003267 +theta=18795.4443 <HelmertIn.txt  >>cctout.txt
</code>
or
<code>
cct -z 0 -o cctout.txt +proj=helmert +convention=coordinate_frame +x=239228.435 +y=6693404.951 +s=1.0003267 +theta=18795.4443 HelmertIn.txt
</code>

on an input file of 8 lines, only the first 7 points are transformed. The last line does not end with CR LF. So I have to add a blank line to get all points. cs2cs works correct on the same input file.

Tested on Windows 7 with PROJ v5.2 from OSGEO4W bianries.

**Comment by kbevers** [comment] 2018-10-29 09:05
@Andre-J Would it be possible for you to attach your file to this issue?

**Comment by kbevers** [comment] 2018-10-29 20:24
Thanks.

I *think* this problem is solved by removing `opt_eof_handler(o);` in the code below. 

https://github.com/OSGeo/proj.4/blob/ce3197ea56e60285f1b67792d2029a36c1a1cdc6/src/cct.c#L338-L346

As far as I can tell `opt_input_loop()` advances the `o->input` to the end of the file while reading the content of the last line. `opt_eof_handler()` then discovers that we have reach the end of the file, before we get to the point where the output is produced.

I am not all that familiar with the `opt_*` functions though. @busstoptaktik can you give this a look and check if this is the proper solution?

**Comment by busstoptaktik** [comment] 2018-10-30 13:09
This is not necessarily a bug, but certainly inconsistent behaviour between cs2cs and cct.

According to cct, **a line ends at crlf** (or whatever your platform prefers). After the last line in [HelmertIn.txt](https://github.com/OSGeo/proj.4/files/2524812/HelmertIn.txt) an incomplete line occurs.

Apparently cs2cs selects to treat the incomplete line as valid, cct does not.

The solution proposed by @kbevers will break the handling of two or more input files (`cct +... file1 file2...`), and emulating the cs2cs behaviour will require some ugly code, which I'm reluctant to add if this is not a common problem - and my first hunch is that it isn't.

My reason for believing this is that I have still not found an editor able to produce a file without crlf at the end of last line (under Windows, I can produce one using the `copy con filename`, ending the incomplete line with ^Z.

So @Andre-J, I suppose your output comes from a program which ends the previous line once it starts writing the next, then "forgets" to finish the last line before it closes the output file.

cct discards incomplete lines by design, which I consider a feature; cs2cs tries to make sense of potentially partial data, which you consider a feature.

I think the point we can probably agree upon is that both cct and cs2cs should warn about incomplete lines. Introducing that feature will probably be about as unelegant as supporting partial lines, but it will serve a more well defined purpose.

**Comment by busstoptaktik** [comment] 2020-01-08 11:26
@Andre-J, I'll close this issue. Feel free to reopen it if you consider submitting a PR implementing the warning functionality discussed above.

**Closed as completed by busstoptaktik** 2020-01-08 11:26 UTC
Labels: enhancement, wontfix, feature request
