### ISSUE TITLE
proj_normalize_for_visualization() for south/west axes

### ISSUE THREAD

**Issue by mbudaj** [OSGeo/PROJ#2299] opened 2020-07-08 19:09 UTC
Currently `proj_normalize_for_visualization()` is applied to swap the axes order in the case of north/east orientation.

It would be really helpful if it worked to change also south/west to west/south order. In a strict sense, it's not a normalization "for visualization", but it would ensure consistency if the input or output coordinate system uses south/west or west/south axes. An example is Krovak's projection, where a recent bugfix #2200 resulted in swapped axes (west/south in 7.0.1, south/west in 7.1.0), which broke the processing of input data in https://github.com/therion/therion, where coordinates are stored in plain text input files.

It would also ensure consistency between the two approaches to conversion given below.

An overview of the current situation (in a simplified pseudocode):
P1: epsg:32634
P2: +proj=krovak +czech +ellps=bessel
source point in P1: 401375.238    5421243.277    2025.437

**Approach 1:**
use `proj_create_crs_to_crs(P1, P2)` and `proj_normalize_for_visualization()`
result in proj 7.0.1: 379161.27 1208937.46 2025.44
result in proj 7.1.0: 1208937.46 379161.27 2025.44

**Approach 2:**
use `proj_create("+proj=pipeline +step +inv +init=epsg:32634 +step +proj=krovak +czech +ellps=bessel")`
result in proj 7.0.1: 379161.27 1208937.46 2025.44
result in proj 7.1.0: 379161.27 1208937.46 2025.44

**Footnote**
Actually, `projinfo "+proj=krovak +czech +ellps=bessel +type=crs"` in 7.1.0 inconsistently gives `+axis=swu` in proj4 representation, but west/south order in WKT2 representation.

**Comment by rouault** [comment] 2020-07-08 22:15
The inconsistency you spot in Footnote was the root cause of the issue, that I've addressed in #2300
This restores the behaviour of proj 7.0.1 with your Approach 1

I haven't touched the proj_normalize_for_visualization() logic, as I'm not sure what to do with southing/westing or westing/southing. In addition to normalizing to west, south order, I guess one might also want to change the sign to be east, north.

**Comment by mbudaj** [comment] 2020-07-09 05:19
Thanks for the fix. By changing the sign, do you mean changing the sign of the coordinates themselves? Just to solve the issue of west/south axes with positive coordinates, there are pairs of CRSs which is I think the right approach; e.g. for Krovak's projection:

EPSG:8352 – south/west axes, positive coordinates
EPSG:8353 – east/north axes, negative coordinates

Actually, EPSG:8352 doesn't respect the traditional order west/south and that's another reason why `proj_normalize_for_visualization()` would be useful for west/south and south/west cases.

**Comment by rouault** [comment] 2020-07-09 14:21
>  By changing the sign, do you mean changing the sign of the coordinates themselves?

Yes, that what was I considering. But on reflection, this is likely not a good idea: this would result in "correct" display for GIS (see this QGIS issue about Transverse Mercator South Orientated : https://github.com/qgis/QGIS/issues/32391 ), at least in north being displayed at top and east at right of the screen, but the change of sign of coordinates would be a problem for positionning

Regarding changing south/west order to west/south in proj_normalize_for_visualization(), I'm not entirely convinced of the benefits of that

**Comment by mbudaj** [comment] 2020-07-09 17:48
> Regarding changing south/west order to west/south in proj_normalize_for_visualization(), I'm not entirely convinced of the benefits of that

It's not useful for visualization, but it would be helpful to keep things simple for the user entering input data or processing output data, because the order of coordinates would not depend on the projection but would be fixed and a simple rule like "enter the coordinate in east-west direction first, then the coordinate in north-south direction" could be used. Something like using proj_normalize_for_visualization() to not have to think if the projection requires lat/long or long/lat.

It would also make possible to easily switch e.g. between `+proj=krovak +czech +ellps=bessel +towgs84=...` and EPSG:8352 (which are really the same thing with the exception of the choice of axes orientation in the EPSG standard) without the need to modify the input data (e.g. in the case of data stored in text files).

**Closed as completed** 2020-09-15 01:22 UTC
Labels: wontfix, feature request
