### ISSUE TITLE
OSX: brew doesn't install cmake scripts

### ISSUE THREAD

**Issue by Nitaym** [OSGeo/PROJ#1484] opened 2019-05-24 02:58 UTC
Installing proj4 using `brew install proj` on OSX doesn't install the cmake scripts

under /usr/local/Cellar/proj/6.1.0/lib there's no cmake directory.
On the cmake script, using `find_package(PROJ4 REQUIRED)` results in the following message:

```
By not providing "FindPROJ4.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "PROJ4", but
  CMake did not find one.

  Could not find a package configuration file provided by "PROJ4" with any of
  the following names:

    PROJ4Config.cmake
    proj4-config.cmake

  Add the installation prefix of "PROJ4" to CMAKE_PREFIX_PATH or set
  "PROJ4_DIR" to a directory containing one of the above files.  If "PROJ4"
  provides a separate development package or SDK, be sure it has been
  installed.

```

**Comment by mwtoews** [comment] 2019-05-24 03:33
This occurred to me the other day too, and it seems that `cmake/ProjConfig.cmake` should be moved back to `cmake/Proj4Config.cmake`.

**Comment by Nitaym** [comment] 2019-05-24 12:48
This works okay if you checkout the git repo and build with cmake. The brew part is the one that has the problem. Isn't using brew the same as doing `make install`? Not sure why this is hapenning

**Comment by kbevers** [comment] 2019-06-24 08:01
Not sure if this is a problem with PROJ or a brew. I haven't seen the above error when I build on OS X. @mwtoews is there any downside to changing the filename back to `Proj4Config.cmake`?

**Comment by mwtoews** [comment] 2019-06-24 09:43
@kbevers investigating more, it seems the file should be moved to either `PROJ4Config.cmake` or `proj4-config.cmake`, but not `Proj4Config.cmake` (i.e. this wouldn't have worked before anyways).

The CMake docs for this are for the [`find_package` command](https://cmake.org/cmake/help/latest/command/find_package.html#command:find_package), which "searches for a file called `<PackageName>Config.cmake` or `<lower-case-package-name>-config.cmake`".

There is probably more work to be done to make this work correctly, as here's what I can do:
```
$ mkdir /tmp/xyz && cd /tmp/xyz
$ cat > CMakeLists.txt
cmake_minimum_required(VERSION 3.5 FATAL_ERROR)
project(xyz LANGUAGES C CXX)
find_package(PROJ4)
$ mkdir build && cd build
$ cmake -DCMAKE_PREFIX_PATH=/path/to/PROJ/cmake/ ..
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
... snip a few lines of output ...
-- Looking for ceil in m
-- Looking for ceil in m - found
CMake Error: File /tmp/xyz/cmake/proj_config.cmake.in does not exist.
CMake Error at /path/to/PROJ/cmake/PROJ4Config.cmake:51 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:3 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/xyz/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/xyz/build/CMakeFiles/CMakeError.log".
```
(and this was with `PROJ4Config.cmake` in `/path/to/PROJ`). The error message refers to [this line](https://github.com/OSGeo/PROJ/blob/726910a811d4fe28884f3f9bfa2b2a14fc66931e/cmake/ProjConfig.cmake#L51), using the relative path to whatever `CMAKE_CURRENT_SOURCE_DIR` is for the hypothetical `xyz` project (rather than from PROJ).

Also, I'll admit that I haven't used `find_package` successfully yet with other packages, so it's certainly possible I'm buggering up something here.

**Comment by kbevers** [comment] 2019-06-24 10:16
Is this maybe caused by the ongoing process of fixing the namespace and project name as described in #789 and https://github.com/OSGeo/PROJ/issues/802 ?

**Comment by iustin94** [comment] 2019-09-25 07:54
I encountered this same issue on Ubuntu 19.04. The installation is done with apt-package manager and the library is added with cmake find_package(PROJ4 REQUIRED).

```
CMake Error at lib/CMakeLists.txt:23 (find_package):
  By not providing "FindPROJ4.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "PROJ4", but
  CMake did not find one.

  Could not find a package configuration file provided by "PROJ4" with any of
  the following names:

    PROJ4Config.cmake
    proj4-config.cmake

  Add the installation prefix of "PROJ4" to CMAKE_PREFIX_PATH or set
  "PROJ4_DIR" to a directory containing one of the above files.  If "PROJ4"
  provides a separate development package or SDK, be sure it has been
  installed.

```

**Comment by autonomobil** [comment] 2019-09-28 00:05
> I encountered this same issue on Ubuntu 19.04. The installation is done with apt-package manager and the library is added with cmake find_package(PROJ4 REQUIRED).
> 
> ```
> CMake Error at lib/CMakeLists.txt:23 (find_package):
>   By not providing "FindPROJ4.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "PROJ4", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "PROJ4" with any of
>   the following names:
> 
>     PROJ4Config.cmake
>     proj4-config.cmake
> 
>   Add the installation prefix of "PROJ4" to CMAKE_PREFIX_PATH or set
>   "PROJ4_DIR" to a directory containing one of the above files.  If "PROJ4"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> ```

same problem, Ubuntu 16.04

**Comment by qswawrq** [comment] 2019-12-10 15:47
> > I encountered this same issue on Ubuntu 19.04. The installation is done with apt-package manager and the library is added with cmake find_package(PROJ4 REQUIRED).
> > ```
> > CMake Error at lib/CMakeLists.txt:23 (find_package):
> >   By not providing "FindPROJ4.cmake" in CMAKE_MODULE_PATH this project has
> >   asked CMake to find a package configuration file provided by "PROJ4", but
> >   CMake did not find one.
> > 
> >   Could not find a package configuration file provided by "PROJ4" with any of
> >   the following names:
> > 
> >     PROJ4Config.cmake
> >     proj4-config.cmake
> > 
> >   Add the installation prefix of "PROJ4" to CMAKE_PREFIX_PATH or set
> >   "PROJ4_DIR" to a directory containing one of the above files.  If "PROJ4"
> >   provides a separate development package or SDK, be sure it has been
> >   installed.
> > ```
> 
> same problem, Ubuntu 16.04

Same issue on 16.06. Proj is installed by apt-get.

**Comment by mwtoews** [comment] 2020-02-02 10:13
I finally had a chance to take a deeper look into this issue, and there does not seem to be any issues for folks on Linux that build PROJ themselves with CMake. I've checked many releases from 4.9.3 through at least 81a83f1142e89171af556141112faae3e9c2fdad (converging towards PROJ 7.0). This means that renaming `Proj4Config.cmake` to `ProjConfig.cmake` didn't do any harm.

For instance, take any PROJ release with CMake support, e.g. PROJ 5.2.0:
```
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/tmp/proj-5.2.0 ..
make
make install
```
then make an example (e.g.) C project that depends on `#include <proj.h>` with a CMakeLists.txt file that uses `find_package(PROJ4 REQUIRED)`, you will need to configure this project with the same `CMAKE_PREFIX_PATH` where PROJ was installed:
```
cmake -DCMAKE_PREFIX_PATH=/tmp/proj-5.2.0 ..
```
or alternatively:
```
cmake -DPROJ4_DIR=/tmp/proj-5.2.0/lib/cmake/proj4 ..
```
the affirmative output should look like:
```
...
-- Reading /tmp/proj-5.2.0/lib/cmake/proj4/proj4-config.cmake
-- PROJ4 configuration, version 5.2.0
-- Configuring done
-- Generating done
...
```
which is great, because the program compiles and links as expected. It would be nice to add a simple CI test, particularly if we do further renaming to various CMake components.

I don't access to macOS, so I can't do a similar check.

----

The root of this issue seems to be around packaged distributions of PROJ, which in many cases was *not* built with CMake, and therefore does not have these CMake configure files installed into `<prefix>/lib/cmake/proj4`, as initially reported.

For instance, looking at [Ubuntu 16.04 (xenial) files for `libproj-dev`](https://packages.ubuntu.com/xenial/amd64/libproj-dev/filelist), the CMake configure files are absent, as I'm 99% certain that the Debian packagers use Autotools to package and distribute libproj via apt. I suspect similar for brew.

A recommended workaround is to build and install PROJ with CMake. The other approach is to convince Debian and Homebrew packagers to change their workflows to use CMake instead of Autotools. Or they can see if there is a workaround to populate the files that are expected in `<prefix>/lib/cmake/proj4`.

Given this issue is with packaged releases from brew and apt, and not PROJ's CMake setup, I recommend closing this ticket.

**Comment by hobu** [comment] 2020-02-02 14:45
> Or they can see if there is a workaround to populate the files that are expected in `<prefix>/lib/cmake/proj4`.

I have worked with commercial SDKs that provide CMake files to describe the layout of the library, headers, etc. They have appeared to be hand-crafted, and defined the necessary targets and variables needed for a CMake user to consume the configuration. 

Another option is to investigate better/proper pkg-config support on the CMake side, but I don't know where that rabbit hole leads.

**Closed as completed** 2020-04-09 16:22 UTC
Labels: wontfix, awaiting_feedback
