### ISSUE TITLE
JNI example throws Exception

### ISSUE THREAD

**Issue by dwschulze** [OSGeo/PROJ#380] opened 2016-05-16 13:00 UTC
Running the JNI example at https://github.com/OSGeo/proj.4/tree/master/jniwrap gives this exception:

Exception in thread "main" java.lang.UnsatisfiedLinkError: org.proj4.PJ.allocatePJ(Ljava/lang/String;)J
    at org.proj4.PJ.allocatePJ(Native Method)
    at org.proj4.PJ.<init>(Unknown Source)
    at main.Main.main(Main.java:17)

The JVM is finding the proj library, but it looks like there may be something missing within the JNI layer itself.

This is from the 4.9.2 .tgz file on the wiki page.  I built it using the instructions on that page:
    CFLAGS=-Iinclude2 ./configure --with-jni=include1

**Comment by hobu** [comment] 2016-05-16 20:15
The maintenance status of the Proj.4 JNI bindings is unknown. It is likely they have not been updated or maintained in a long time, and it is possible there is some bitrot to be cleaned up.

**Comment by larsnaesbye** [comment] 2017-03-07 00:24
I can confirm this is a problem. The proj.dll is there in my Java path, and I can load other DLLs using System.loadLibrary, but even with the OSGeo4W64 bundled proj.dll I get this error.

**Comment by larsnaesbye** [comment] 2017-11-10 09:42
No, sorry. I moved transformation further back in the software stack, avoiding the problem.

**Comment by kbevers** [comment] 2018-05-07 20:57
@desruisseaux is this problem fixed with #957 or #969 ?

**Comment by kbevers** [comment] 2018-05-23 12:14
I am closing this on the basis that @desruisseaux do not have the problem and no one else has reproduced the problem since the recent updates of the JNI bindings. Should the issue show up in the future I'll reopen the issue.

**Closed as completed by kbevers** 2018-05-23 12:14 UTC
Labels: bug
