### ISSUE TITLE
configure file is missing

### ISSUE THREAD

**Issue by dwschulze** [OSGeo/PROJ#379] opened 2016-05-15 22:36 UTC
The title says it all.  If you don't intend for us to build with ./configure you need to update the docs.

**Comment by QuLogic** [comment] 2016-05-15 22:44
Dupe of #352.

**Comment by dwschulze** [comment] 2016-05-16 12:50
Then the README should be updated.  No one will know to look at issue 352.

**Closed as completed** 2016-05-16 20:14 UTC
