### ISSUE TITLE
testntv2 does not pass with grids installed

### ISSUE THREAD

**Issue by QuLogic** [OSGeo/PROJ#1299] opened 2019-02-27 11:13 UTC
With proj-datumgrid-north-america-1.2RC2 installed (i.e., `ntv2_0.gsb`), `testntv2` runs, but does not pass:
```
============================================
Running ../../test/cli/testntv2 using ../../src/cs2cs:
============================================
doing tests into file ntv2_out, please wait
diff ntv2_out with ntv2_out.dist
10c10
< 111d00'00.000"W 46d00'00.000"N 0.0    111d0'3.1897"W    45d59'59.7489"N 0.000
---
> 111d00'00.000"W 46d00'00.000"N 0.0    111d0'3.1549"W    45d59'59.7528"N 0.000
```

**Comment by kbevers** [comment] 2019-03-06 22:35
Once #1314 is in a proper state I will migrate the test data from `testntv2` to the gie framework. gie gives better control of what to do when grids are missing. I believe this is a trivial fix.

**Comment by QuLogic** [comment] 2020-01-08 22:25
This is fixed by #1822, I think, and thus not `wontfix`.

**Comment by QuLogic** [comment] 2020-01-08 22:26
> [<img alt="@stale" width="20" height="20" src="https://avatars2.githubusercontent.com/in/1724?s=60&amp;v=4">](https://github.com/marketplace/stale) [stale](https://github.com/marketplace/stale) bot removed the [wontfix](/OSGeo/PROJ/labels/wontfix) label [34 seconds ago](#event-2932943819)

Would be a bit less churn if stale-bot only added that when it closed the issue.

**Comment by kbevers** [comment] 2020-01-09 07:21
> This is fixed by #1822, I think, and thus not wontfix.

Let's just close the issue then!

> Would be a bit less churn if stale-bot only added that when it closed the issue.

Do you get notifications when it changes labels? If not, I don't think we should try to change this. Provided that is even possible, I believe the bot monitors issues based on last time of activity and attached labels.

**Closed as completed by kbevers** 2020-01-09 07:21 UTC

**Comment by QuLogic** [comment] 2020-01-09 07:31
No, I don't think so, but I had the issue open when it did it, and for the rest, there was a comment, so I would get a notification anyway.

**Comment by kbevers** [comment] 2020-01-09 07:36
And the comment by the bot is there by design, so probably nothing that can be done to improve your experience. With that said, it's a new addition to the repository and if it turns out to be more of a nuisance than help it will go away again. Too early to make that call now.

**Comment by QuLogic** [comment] 2020-01-09 07:46
Right, the comments are only a small initial pain anyway.
