### ISSUE TITLE
unitconvert yyyymmdd to decimalyear error

### ISSUE THREAD

**Issue by trey-stafford** [OSGeo/PROJ#1483] opened 2019-05-23 23:21 UTC
I noticed some unusual results from using `cct` with unitconvert steps. The conversion from yyyymmdd to decimalyear appears to be wrong in some cases.

1990-01-02 becomes 1990-01-01:
```
$ echo "-117.61748591770593, 59.496749040316935, 329.39612, 19900102" | cct -d 14 +proj=pipeline \
>   +step +proj=unitconvert +t_in=yyyymmdd +t_out=decimalyear \
>   +step +proj=unitconvert +t_in=decimalyear +t_out=yyyymmdd
-117.61748591770592  59.49674904031694  329.39612000000000  19900101.0000
```
Converting 1990-01-02 to a decimal years gives 1990.0027. 
```
$ echo "-117.61748591770593, 59.496749040316935, 329.39612, 19900102" | cct -d 14 +proj=pipeline \
>   +step +proj=unitconvert +t_in=yyyymmdd +t_out=decimalyear
-117.61748591770592  59.49674904031694  329.39612000000000     1990.0027
```
I believe the result should be 1990.0041:
```
$ echo "-117.61748591770593, 59.496749040316935, 329.39612, 1990.0041" | cct -d 14 +proj=pipeline \
>   +step +proj=unitconvert +t_in=decimalyear +t_out=yyyymmdd
-117.61748591770592  59.49674904031694  329.39612000000000  19900102.0000
```
Note that using `+inv` _does_ provide the correct result:
```
$ echo "-117.61748591770593, 59.496749040316935, 329.39612, 19900102" | cct -d 14 +proj=pipeline \
>   +step +proj=unitconvert +t_in=yyyymmdd +t_out=decimalyear \
>   +step +inv +proj=unitconvert +t_in=yyyymmdd +t_out=decimalyear
-117.61748591770592  59.49674904031694  329.39612000000000  19900102.0000
```

I am using proj4 v6.1.0 installed via conda:
```
$ conda list proj4
# packages in environment at /home/trst2284/miniconda3/envs/valkyrie:
#
# Name                    Version                   Build  Channel
proj4                     6.1.0                he751ad9_2    conda-forge
```

**Comment by kbevers** [comment] 2019-05-24 08:58
Bug confirmed with http://sopac-old.ucsd.edu/convertDate.shtml

**Comment by kbevers** [comment] 2019-05-24 09:12
The fix to this should also include an update to `gie` that allows checking temporal component of returned and expected coordinates. At the moment `gie` ignores the time in the check.

**Comment by direvus** [comment] 2021-11-04 23:49
@kbevers it seems like that SOPAC converter you linked is taking a date to mean the midpoint of that day (12:00 noon), whereas PROJ is taking it to mean the beginning of that day (00:00 midnight).

SOPAC converts 2020-01-01 to 2020.0014, which is 12 hours into 2020.
PROJ converts 2020-01-01 to 2020.000, the very beginning of 2020.

SOPAC converts 2020-12-31 to 2020.9986, 12 hours before the end of 2020.
PROJ converts 2020-12-31 to 2020.9973, 24 hours before the end of 2020.

Is there any standard or authority on how this "decimal year" thing is supposed to work exactly?  Searching only got me various boutique software implementations of it.  The midnight approach made intuitive sense to me.  Most software datetime libraries I've worked with will assume 00:00 if you don't specify a time of day. But if the 12 noon approach is the correct one for "decimal year", then perhaps we should update PROJ to match.

**Comment by kbevers** [comment] 2021-11-05 06:22
> Is there any standard or authority on how this "decimal year" thing is supposed to work exactly?

Not that I'm aware of. I haven't come across it in my work with geodesy but I could easily have missed it. In the end I don't think it matters much at this point. We mainly use the decimal year in transformations that deal with deformations that are measured in mm/yr, a rounding error of half a day won't matter much. But if people start to use it in transformations that are valid in the early hours after an earthquake we will be in trouble. 

The minimum effort here would be to just document the behaviour. It could make sense to confer with the mailing list and see if someone knows if there is actually a preferred way to do this.

**Comment by direvus** [comment] 2021-11-18 22:35
Well at the very least I feel we ought to do something about date -> decimalyear -> date returning a different value as mentioned in the OP.  I have a hunch that adopting the "12 noon" method for decimalyear may fix that bug.  I might tinker with it and see if I can prove that.

**Comment by kbevers** [comment] 2021-11-19 06:49
> I might tinker with it and see if I can prove that.

Sounds great!

**Comment by direvus** [comment] 2021-12-10 04:39
So I was able to solve the OP's problem by adding 12 hours to the decimal year output in mjd_to_decimalyear().  That works fine for cases where the input is a date only, but breaks other cases where the input is a datetime.

Because unitconvert.cpp doesn't have any way to distinguish between a true "date" and a "datetime" (it all gets converted internally into "datetime", represented as floating point), I don't think there is any simple solution that will work for everybody.  Whatever we do, we end up with either silly behaviour for dates, or silly behaviour for datetimes.

The only way I can see to properly solve it would be to have separate code paths for date and datetime values.  For datetime values, basically keep doing what we're doing.  For date values, maybe convert them to a (int year, int month, int day) struct and use that as the internal representation instead of floating point MJD.

But that would be a fairly invasive change, with a good chance of producing surprising behaviours in other scenarios, so I can't say I am extremely keen to go ahead with it.  I'm starting to come around to the "just document the behaviour" idea.

**Comment by kbevers** [comment] 2021-12-10 09:52
> I'm starting to come around to the "just document the behaviour" idea.

Sounds good to me!

**Comment by direvus** [comment] 2022-03-11 00:07
I have spent a bit more time playing around with decimalyear -> date conversion and I now think that at bottom, there's a truncation/rounding issue when we convert from MJD into YYYYMMDD.

2022-01-02 converted into decimalyear gets output as "2022.0027", but at 4 decimal places, you lose substantial precision for datetimes.  The internal float value before rounding is more like 2022.0027397260273972603.  If you take that full precision value and convert it back to a date, you do indeed get the correct answer of January 2nd.

However, if you take the rounded value 2022.0027 and use it in a further calculation, that is only equivalent to 0.9855 of a full day since the beginning of 2022, approximately January 1st at 23:39:07.

When unitconvert goes from MJD to YYYYMMDD, it truncates off any fractional part of the day, so 23:39:07 on January 1st yields just January 1st.

Truncation seems like a reasonable approach for dates in general, but when the input is a floating-point number of days with a fractional time component, that might have already been subject to some rounding, maybe we ought to be rounding to the nearest day instead.

I have been experimenting with a patch that modifies mjd_to_yyyymmdd() to round instead of truncate, and it appears to be working perfectly for the OP's case.  It also passes all the existing unit tests, so it seems like a lot less disruptive of a change than my earlier "12 noon" attempt.

**Closed as completed** 2022-03-14 19:38 UTC
Labels: bug
