### ISSUE TITLE
Proj initialization failure: conic lat_1 = -lat_2

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1209] opened 2018-12-27 01:44 UTC
When running using `+proj=aea` it works just fine :
```
$ ./pyproj/proj_dir/bin/proj +proj=aea
-30 40             
-2496723.89	4643445.99
```
However, if I use the output from projinfo:
```
$ ./pyproj/proj_dir/bin/projinfo +proj=aea
PROJ string:
+proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=aea +lat_0=0 +lon_0=0 +lat_1=0 +lat_2=0 +x_0=0 +y_0=0 +ellps=WGS84
...
```
I get:
```
$ ./pyproj/proj_dir/bin/proj +proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=aea +lat_0=0 +lon_0=0 +lat_1=0 +lat_2=0 +x_0=0 +y_0=0 +ellps=WGS84
Rel. 6.0.0, March 1st, 2019
<proj>: 
projection initialization failure
cause: conic lat_1 = -lat_2
program abnormally terminated
```
I ran into this and thought it was noteworthy, so I figured I would share it. If the behavior is expected, feel free to close the issue. Thanks!

**Comment by rouault** [comment] 2018-12-27 08:36
@kbevers I figured out the issue. It turns out that it is due to proj_def.dat having lat_1=29.5 and lat_2=45.5 for proj=aea. The ISO-19111 code doesn't use proj_def.dat directly or indirectly and thus initialize lat_1 and lat_2 to 0. I'd note that  https://proj4.org/operations/projections/aea.html also indicates 0 as the default value. Do we still want to honour proj_def.dat ?

**Comment by kbevers** [comment] 2018-12-27 08:38
> Do we still want to honour proj_def.dat ?

No: https://github.com/OSGeo/proj.4/issues/201

**Comment by kbevers** [comment] 2018-12-27 08:44
Also, if you adjust the parameters of `aea` to avoid the failure, you still end up having problems with input types for PROJ:

```
$ ./bin/proj +proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=aea +lat_0=0 +lon_0=0 +lat_1=10 +lat_2=20 +x_0=0 +y_0=0 +ellps=WGS84
Rel. 6.0.0, March 1st, 2019
<proj>:
can't initialize operations that take non-angular input coordinates
program abnormally terminated
```

This is similar to the problem described in https://github.com/OSGeo/proj.4/pull/1205. I *think* the best solution is to replace `PJ_IO_UNITS_ANGULAR` with `PJ_IO_UNITS_DEG` and `PJ_IO_UNITS_RAD`. This is somewhat going back to the initial implementation of the input/output operation units but to me it seems like the simplest way to have pipelines such as the one above work in both `proj`, `cs2cs` and `cct`. The alternative is to completely rewire all the projections to use degrees instead of radians internally and I don't really want to do that.

**Comment by rouault** [comment] 2018-12-27 09:06
Closing as a duplicate of #201 and #1205

**Closed as completed by rouault** 2018-12-27 09:06 UTC
