### ISSUE TITLE
Error no longer given for out of range coordinates

### ISSUE THREAD

**Issue by ojwb** [OSGeo/PROJ#1524] opened 2019-06-22 05:00 UTC
I would expect a request to convert a point near the south pole to OSGB (which a UK-specific projection) to fail with an error.

However with proj 6.1.0 it appears to succeed:

```
$ echo 179 -89 1000|cs2cs +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +to +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=0 +y_0=0 +ellps=airy +datum=OSGB36 +units=m +no_defs
-1842.61	-15536258.81 1000.00
```

This is a regression compared to older versions which give a helpful error - e.g. with 5.2.0:

```
$ echo 179 -89 1000|cs2cs +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +to +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=0 +y_0=0 +ellps=airy +datum=OSGB36 +units=m +no_defs
Rel. 5.2.0, September 15th, 2018
<cs2cs>: while processing file: <stdin>, line 1
pj_transform(): latitude or longitude exceeded limits
*	* 2175.53
```

**Comment by rouault** [comment] 2019-06-22 08:32
This is not a regression. In PROJ 6, tmerc uses the Extended Transverse Mercator algorithm (etmerc) which is able to transform anywhere on the globe with accuracy.

If you chain your transformation with the inverse one, you'll almost retrieve your initial point:
```
$ echo 179 -89 1000| cs2cs +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +to +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=0 +y_0=0 +ellps=airy +datum=OSGB36 +units=m +no_defs | cs2cs -I +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +to +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=0 +y_0=0 +ellps=airy +datum=OSGB36 +units=m +no_defs
179d0'0.048"E	89d0'0.003"S 1000.000
```
If you want PROJ < 6 behaviour with tmerc, you need to add a +approx flag in the parameters of +proj=tmerc
```
$ echo 179 -89 1000| cs2cs +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +to +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=0 +y_0=0 +ellps=airy +datum=OSGB36 +units=m +no_defs +approx
*	* inf
```

**Comment by ojwb** [comment] 2019-06-24 04:42
Ah I see, thanks for the explanation.

Can I just pass `+approx` unconditionally and rely on this working with old versions of proj too?  From experimenting it looks like unknown `+foo` flags in the parameter string are ignored, but I don't see anything in the documentation about that.

For background, what I'm actually using this for is to deliberately trigger an error when converting from one coordinate system to another via the API in an automated testcase that's intended to check my application reports an error from proj in a suitable way.  The second coordinate system needs to satisfy `!pj_is_latlong(pj)` (in the old API - I'm currently just trying to get things to work fully with PROJ6 before updating the API usage).

**Comment by kbevers** [comment] 2019-06-24 07:31
> Can I just pass +approx unconditionally and rely on this working with old versions of proj too? From experimenting it looks like unknown +foo flags in the parameter string are ignored, but I don't see anything in the documentation about that.

Earlier versions of PROJ will just ignore the `+approx` flag, so yes you can do that. I wouldn't recommend that way of discovering incorrect usage of transformations between CRS's. Instead you should leverage the plethora of new features in PROJ 6 that, amongst others, let you check the recommended area of use of a given transformation. Consult the [docs](https://proj.org/development/reference/functions.html#c-api-for-iso-19111-functionality) for more on the subject.

I am closing this ticket since the original issue is a deliberate change in behaviour. Feel free to continue the discussion.

**Closed as completed by kbevers** 2019-06-24 07:31 UTC

**Comment by ojwb** [comment] 2019-06-24 23:57
Thanks for the confirmation that `+approx` will work for my testcase.

I'm not currently trying to explicitly diagnose such incorrect use, just to relay any error that proj gives.  But it would be a useful enhancement to check for that explicitly so thanks for the pointer.

I'm certainly happy with the resolution of this ticket.
