### ISSUE TITLE
Add public API method to query active EPSG db version 

### ISSUE THREAD

**Issue by hobu** [OSGeo/PROJ#471] opened 2016-12-19 20:10 UTC
Add something like  `char* pj_get_epsg_version()` to return a string representing the currently active EPSG db.

**Comment by rouault** [comment] 2016-12-19 20:19
The fun fact is that proj.4 doesn't know anything about the EPSG database. "epsg" is just a resource file. We could imagine to have a special header in such files like

`# version: X.Y.Z`

that could be used by `char* pg_get_dict_version(const char* dict_name)`

That way that would work for other dictionaries that could potentially be versionned.

**Comment by busstoptaktik** [comment] 2016-12-20 08:43
I think a special transformation in the top of the epsg file would work:

    <version> +proj=longlat  +a=X  +b=Y.Z  +no_defs <>

Then by doing an `+init=epsg:version`  one would obtain the major version as the semimajor axis, the minor version/revision the semiminor axis of the ellipsoid.

The syntax `epsg:version` seems straightforward and natural. The overloading of the meaning of the ellipsoidal defining parameters may stir some discussion.

It would, however, work out-of-the box, with just a single line patch to the `nad/epsg` file

**Comment by kbevers** [comment] 2016-12-20 09:20
@busstoptaktik That's a bit too clever for my liking. I am more in favour of @rouault's suggestion.

**Comment by busstoptaktik** [comment] 2016-12-20 11:32
The scope of my suggestion is actually much wider (like it or not :-) ): The main aim is to avoid API sprawl by drawing inspiration from the Unix "everything is a file" concept, by saying that in proj.4 "everything is a projection".

As also mentioned above, we might implement it differently than by overloading the meaning of the ellipsoidal parameters. By defining generic information accessors, we can have a generic interface to library versions and resource file versions by saying something like:

    int major, minor, patch;

    PJ *P = pj_init ("+proj=version");

    major = pj_info (P, PJ_VERSION_MAJOR);
    minor = pj_info (P, PJ_VERSION_MINOR);
    patch = pj_info (P, PJ_VERSION_PATCH);

    P = pj_init ("+init=epsg:version");
    major = pj_info (P, PJ_VERSION_MAJOR);
    ...

    P = pj_init ("+init=IGNF:version");
    major = pj_info (P, PJ_VERSION_MAJOR);
    ...

    P = pj_init ("+init=esri:version");
    major = pj_info (P, PJ_VERSION_MAJOR);
    ...

    P = pj_init ("+init=esri.extra:version");
    major = pj_info (P, PJ_VERSION_MAJOR);
    ...

Here, `pj_info` is a hypothetical information accessor, that accesses material that the individual projection may make available. In this case, the projection `+proj=version` by default supplies the version triplet of the proj.4 library, and accepts options to set other triplet values.

Hence, each ressource file may define its own section:

    <version> proj=version major=42 minor=314 patch=272 +no_defs <>

And we will have a unified way of numbering and accessing all ressource files, without incurring API sprawl.

This probably generalizes to other uses, that would otherwise require API extensions. I am all for keeping the API slim (hence my efforts in `pj_obs_api.c` and `proj.h`), and I find it natural to do this by introducing the "everything is a projection" dogma in a library that is natively about projections: Adding another special purpose projection is much less intrusive, architectually speaking, than adding yet another special purpose information accessor to the API.

**Comment by kbevers** [comment] 2016-12-20 12:05
What I didn't like was storing version numbers as ellipsoid parameters. I like your elaborated version better. Especially if we move datum and ellipsoid definitions to init-files as well. That would make it possible to access that information via the public API (you can do it with ```projects.h``` but it is not recommended). It would also allow users to define their own datum and ellipsoid aliases locally, essentially enabling a shorthand version of parameter sets that you would otherwise have to look.

An added bonus is that issues #220 #187 #173 #155 #17 can be resolved by implementing ```pj_info``` and moving datum/ellipsoid info to an init-file. I think it is worth considering.

**Comment by rouault** [comment] 2016-12-20 12:12
The Unix approach "everything is a file" has sometimes been abused (some Linux interfaces are exposed as files but with tons of ioctl() because read/write doesn't make sense for those fake files), and I feel like it would be the same to have a +proj=version. Such 'projection' couldn't be used for anything else than pj_info(). In particular it could not be used to do coordinate transformation, which is a clear sign that the projection abstraction isn't the best fit.

**Comment by busstoptaktik** [comment] 2016-12-20 12:44
A `proj=version` could not be used for anything else than `pj_info()` (or similar accessors), but the opposite is not true: Both ordinary and special type projections may make information available through a `pj_info()`-style interface. Especially, it will be a way of inspecting the setup information for *any* `PJ` object.

I think maybe the problem is more in the tag name `+proj` than whether the projection abstraction is the best fit or not since

1. The `PJ` object is not about projections *per se*, but about holding and providing access to *state*.
2. The `pj_init*` API is the interface for providing, in clear text, the amount of *state* that is to be held by the `PJ` object, while
3. The `proj=xxx` tag is about selecting what state-interpretation code to invoke to make sense of the remaining part of the cleartext state (the projection setup functions are really state compilers).

Hence, while mnemonically the type name `PJ` and the tag `+proj=xxx` hint at projections, it really is just about state. Hence each time you read `PJ` you might as well say `STATE`, and each time you read `proj=xxx` you might as well say `handler=xxx`.

It is not a matter of whether it makes sense to invoke a `pj_fwd()` call on a `PJ` object representing `proj=version` style state - it's just the matter, that for certain types of state it makes sense to invoke `pj_fwd()` calls, for others it makes sense to invoke `pj_info()` style calls, and for a large group both kinds of calls make sense.

**Closed as completed** 2017-08-07 08:37 UTC
