### ISSUE TITLE
GRS80 ellipsoid seems to be equal to WGS84

### ISSUE THREAD

**Issue by GwennaelM** [OSGeo/PROJ#829] opened 2018-02-28 09:11 UTC
Hi

I'm not an expert in PROJ.4 usage, so I apologize if this issue is not a bug.

As conversions using WGS84 and GRS80 ellipsoids give the same results, it seems their parameters are equals when they should be different (~0.1mm for minor semi-axis).

Here an example:
```
echo "2.5 43.5 10" | cs2cs -f %5.15f +proj=lonlat +ellps=WGS84 +towgs84=0,0,0 +to +proj=lonlat +ellps=GRS80 +towgs84=0,0,0
2.500000000000000	43.500000000000007 10.000000000000000
```

This works fine with Clarke 80:
```
echo "2.5 43.5 10" | cs2cs -f %5.15f +proj=lonlat +ellps=WGS84 +towgs84=0,0,0 +to +proj=lonlat +ellps=clrk80 +towgs84=0,0,0
2.500000000000000	43.503140817107521 63.170659539289773
```

But I don't really understand why I need to add the +towgs84 parameters... My mistake is maybe here. Same example as above but without +towgs84:
```
echo "2.5 43.5 10" | cs2cs -f %5.15f +proj=lonlat +ellps=WGS84 +to +proj=lonlat +ellps=clrk80
2.500000000000000	43.500000000000007 10.000000000000000
```

Tested on v4.9.3.

Thanks

**Comment by busstoptaktik** [comment] 2018-02-28 10:01
@GwennaelM: By design the ``pj_transform()``, and hence ``cs2cs``, considers WGS84 and GRS80 ellipsoids identical: See the [comment in these lines](https://github.com/OSGeo/proj.4/blob/master/src/pj_transform.c#L560-566) of ``pj_compare_datums``.

So this is the intention in the old API, where the aim of the datum handling code is to make it easy to use, even for people without much knowledge of reference frames and geodesy in general.

The new API (in ``proj.h``) provides much more fine grained control over datum shifts (reference frame transformations), but is also somewhat more demanding wrt. the geodetic knowledge required.

The thing you are attempting can be done using ``cct``, the command line interface to the new API:

    $ echo 2.5 43 10 0 | cct +proj=pipeline +step +proj=cart +ellps=WGS84 +step +inv +proj=cart +ellps=GRS80
    > 2.5000000000   43.0000000009       10.0000        0.0000

Where you see the difference in the last decimal of the latitude.

As you have posted this as an issue, I hope to have conviced you that it is not, and I will close the issue with this comment.

If, on the contrary, what you wanted was to discuss the subject, please repost to the [PROJ mailing list](http://lists.maptools.org/mailman/listinfo/proj), where you are more likely to get a discussion going.

**Closed as completed by busstoptaktik** 2018-02-28 10:01 UTC
